let a = 10;
let b = 2;

try{
    console.log("Sum: ", a + c);
}catch(error){
    console.log("Erro: ", error);
} 
